### ISSUE TITLE
Random snippet from all tag.

### ISSUE THREAD

**Issue by drobati** [sQVe/30s#224]
I would love support for a single random snippet from ALL available snippets.

I also would love to implement this if the help is wanted.

**Comment by drobati** [comment]
I took a look last night, and I think adding an option `-r n` where n can be a quantity then passing that to the printer would be a decent solution? Thoughts? I'd love to submit a PR.

**Comment by sQVe** [comment]
@drobati Sorry for getting back at you so late. I totally forgot to put this repo on **watch**. Your feature request would be quite easy to implement but what is your real use-case? I do not want to bloat the API for something that is rarely used.

**Comment by drobati** [comment]
@sQVe I wanted to put it at the end of my .bashrc, so that every new terminal would output a snippet to digest. I looked at using jq, but jq didn't support random selection. Even then it's also limited by tags. It would be neat to do randomization on different degrees of filtering.

**Comment by sQVe** [comment]
@drobati This feature is now released. Use `30s random` to view a random snippet.

**Comment by drobati** [comment]
Nice!

**Comment by drobati** [comment]
![30sexample](https://user-images.githubusercontent.com/132388/59803669-30b12980-92ba-11e9-99b7-c42cff1ceb93.gif)

**Comment by drobati** [comment]
Just plugged it in, works great! Thanks for supporting --layout with it too.
